services:
  db:
    image: hub-pg:latest
    environment:
      POSTGRES_DB: hub
      POSTGRES_USER: hub
      POSTGRES_PASSWORD: ${DB_PASS:-hub}
    ports:
      - "5432:5432"
    volumes:
      - hub-pgdata:/var/lib/postgresql

volumes:
  hub-pgdata: