-- Real entries from the ROPS Krakow Biblioteka Innowacji Spolecznych (public catalog,
-- CC-BY materials) + national helplines. source_url/video_url are real links scraped
-- from rops.krakow.pl on 2026-10-03. Summaries marked (kat.) are catalog category labels,
-- not invented descriptions; the detail page carries the full description.

insert into innovation (title, summary, description, target_group, status, region, video_url, source_url, area_id)
select v.title,
       v.summary,
       v.description,
       v.target_group,
       'WDROZONA',
       v.region,
       v.video_url,
       v.source_url,
       (select id from challenge_area where name = v.area)
from (values ('BaWita',
              'Tablica manipulacyjno-terapeutyczna dla seniorow i osob z chorobami demencyjnymi',
              'Tablica manipulacyjno-terapeutyczna dla seniorow i osob z chorobami dementywnymi. Innowacja wybrana do upowszechniania w ramach projektu Inkubator Wlaczenia Spolecznego.',
              'Seniorzy, osoby z demencja', 'malopolska',
              'https://www.youtube.com/watch?v=o7UhDlebLJo',
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,bawita',
              'Starzenie sie spoleczenstwa'),

             ('Senior CUDER',
              'Innowacja dla seniorow (kat. dla seniorow) - szczegoly na stronie Biblioteki',
              'Pozycja z Biblioteki Innowacji Spolecznych ROPS Krakow, kategoria: dla seniorow. Film prezentacyjny i materialy do pobrania dostepne na stronie innowacji.',
              'Seniorzy', 'malopolska',
              'https://www.youtube.com/watch?v=o5TP10ZStNA',
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,senior-cuder',
              'Starzenie sie spoleczenstwa'),

             ('Merkury',
              'Symulator kioskow samoobslugowych',
              'Symulator kioskow samoobslugowych uczacy obslugi urzadzen dotykowych stosowanych w urzedach, bankach i na dworcach. Pomaga seniorom przezlac strach przed e-uslugami.',
              'Seniorzy', 'malopolska',
              'https://www.youtube.com/watch?v=BK6a8fjELR0',
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,merkury',
              'Wykluczenie cyfrowe'),

             ('Przenosne, modularne lazienki',
              'Mobilne, skladane lazienki dla osob o ograniczonej mobilnosci',
              'Pozycja z Biblioteki Innowacji Spolecznych ROPS Krakow (kat. dla seniorow / osob o ograniczonej mobilnosci). Film i materialy na stronie innowacji.',
              'Osoby o ograniczonej mobilnosci, seniorzy', 'malopolska',
              'https://www.youtube.com/watch?v=Pl5bkpxEqgs',
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,przenosne-modularne-lazienki',
              'Dostep do uslug spolecznych'),

             ('Sciezka motosensoryczna',
              'Ściezka rozwijajaca sprawosc ruchowa (kat. dla seniorow)',
              'Pozycja z Biblioteki Innowacji Spolecznych ROPS Krakow (kat. dla seniorow). Film i materialy na stronie innowacji.',
              'Seniorzy', 'malopolska',
              'https://www.youtube.com/watch?v=4DKP0XK440U',
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,sciezka-motosensoryczna',
              'Starzenie sie spoleczenstwa'),

             ('Kody QR na pomoc seniorom',
              'Kody QR w przestrzeni publicznej prowadzace seniorow do informacji o pomocy',
              'Pozycja z Biblioteki Innowacji Spolecznych ROPS Krakow (kat. dla seniorow). Szczegoly na stronie innowacji.',
              'Seniorzy', 'malopolska',
              null,
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,kody-qr-na-pomoc-seniorom',
              'Wykluczenie cyfrowe'),

             ('Mobilne centrum pomocy dla osob starszych',
              'Mobilna placowka docierajaca z pomoc do osob starszych',
              'Pozycja z Biblioteki Innowacji Spolecznych ROPS Krakow (kat. dla seniorow). Szczegoly na stronie innowacji.',
              'Seniorzy', 'malopolska',
              null,
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,mobilne-centrum-pomocy-dla-osob-starszych',
              'Dostep do uslug spolecznych'),

             ('Wirtualne izby pamieci',
              'Wirtualne przestrzenie wspierajace osoby z demencja i ich bliskich',
              'Pozycja z Biblioteki Innowacji Spolecznych ROPS Krakow (kat. dla seniorow). Szczegoly na stronie innowacji.',
              'Osoby z demencja, opiekunowie', 'malopolska',
              null,
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,wirtualne-izby-pamieci',
              'Starzenie sie spoleczenstwa'),

             ('Korytarz wspomnien',
              'Innowacja wspierajaca terapie wspomnien (kat. dla seniorow)',
              'Pozycja z Biblioteki Innowacji Spolecznych ROPS Krakow (kat. dla seniorow). Szczegoly na stronie innowacji.',
              'Seniorzy, osoby z demencja', 'malopolska',
              null,
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,korytarz-wspomnien',
              'Starzenie sie spoleczenstwa'),

             ('Centrum antydepresyjne',
              'Wsparcie dla osob w depresji (kat. dla seniorow)',
              'Pozycja z Biblioteki Innowacji Spolecznych ROPS Krakow (kat. dla seniorow). Szczegoly na stronie innowacji.',
              'Osoby w depresji', 'malopolska',
              null,
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,centrum-antydepresyjne',
              'Zdrowie psychiczne'),

             ('koMIX zyciowy',
              'Gra terapeutyczna dla wychowankow placowek opiekuńczo-wychowawczych',
              'Gra terapeutyczna dla wychowankow placowek opiekuńczo-wychowawczych. Innowacja wybrana do upowszechniania w ramach projektu Inkubator Wlaczenia Spolecznego.',
              'Dzieci i mlodziez w pieczy zastepczej', 'malopolska',
              'https://www.youtube.com/watch?v=hohm7FnsukY',
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-dzieci-mlodziezy-i-rodziny',
              'Zdrowie psychiczne'),

             ('Patryk i Kropka',
              'Opowiadania latwe do czytania i rozumienia dla mlodziezy z niepelnsprawnoscia intelektualna',
              'Opowiadania ETR (latwe do czytania i rozumienia) dla mlodziezy z niepelnsprawnoscia intelektualna. Innowacja wybrana do upowszechniania w ramach Inkubatora Wlaczenia Spolecznego.',
              'Mlodziez z niepelnsprawnoscia intelektualna', 'malopolska',
              'https://youtu.be/JfmyToWVuOs',
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-dzieci-mlodziezy-i-rodziny',
              'Wykluczenie cyfrowe'),

             ('Edki - kredki terapeutyczne',
              'Kredki terapeutyczne dla dzieci ze spastycznoscia konczyny gornej',
              'Kredki terapeutyczne dla dzieci ze spastycznoscia konczyny gornej. Innowacja wybrana do upowszechniania w ramach Inkubatora Wlaczenia Spolecznego.',
              'Dzieci z niepelnsprawnoscia ruchowa', 'malopolska',
              'https://www.youtube.com/watch?v=ev173g-d_vA',
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-dzieci-mlodziezy-i-rodziny',
              'Dostep do uslug spolecznych'),

             ('Puzzle 3D Braille',
              'Puzzle 3D wspomagajace nauke alfabetu Braille''a',
              'Zabawki edukacyjne (puzzle 3D) wspomagajace nauke alfabetu Braille''a dzieci i mlodziezy z dysfunkcja wzroku. Innowacja z Inkubatora Dostepnosci.',
              'Dzieci z dysfunkcja wzroku', 'malopolska',
              'https://www.youtube.com/watch?v=T_OM-4WqGzE',
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-dzieci-mlodziezy-i-rodziny',
              'Dostep do uslug spolecznych'),

             ('Bez presji z depresji',
              'Komplet materialow psychoedukacyjnych dla dzieci i mlodziezy w kryzysach psychicznych',
              'Komplet materialow psychoedukacyjnych wspierajacych dzieci i mlodziez szkolna doswiadczajacych kryzysow psychicznych.',
              'Dzieci i mlodziez w kryzysie', 'malopolska',
              null,
              'https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-dzieci-mlodziezy-i-rodziny',
              'Zdrowie psychiczne'),

             ('Telefon zaufania 116 111',
              'Bezpłatny, anonimowy, calodobowy telefon zaufania dla dzieci i mlodziezy',
              'Telefon zaufania dla dzieci i mlodziezy prowadzony od 15 lat przez Fundacje Dajemy Dzieciom Sile. Anonimowy, bezplatny, calodobowy; dostepny rowniez jako czat i wiadomosc online.',
              'Dzieci i mlodziez do 18 r.z.', 'Polska',
              null,
              'https://116111.pl/',
              'Zdrowie psychiczne'),

             ('Telefon Wsparcia 800 70 2222',
              'Bezpłatny calodobowy telefon wsparcia dla doroslych w kryzysie psychicznym',
              'Calodobowy, bezplatny telefon wsparcia dla osob doroslych doswiadczajacych kryzysu psychicznego, prowadzony przez Fundacje ITAKA.',
              'Dorozy w kryzysie psychicznym', 'Polska',
              null,
              'https://800702222.pl/',
              'Zdrowie psychiczne'),

             ('Niebieska Linia 800 120 002',
              'Telefon i czat dla osob doswiadczajacych przemocy',
              'Bezpłatna, calodobowa linia pomocowa dla osob doswiadczajacych przemocy w rodzinie, prowadzona przez Centrum Praw Mlodziezy i Ofiar.',
              'Ofiary przemocy', 'Polska',
              null,
              'https://www.niebieskalinia.pl/',
              'Zdrowie psychiczne')) as v(title, summary, description, target_group, region, video_url, source_url,
                                          area)
where not exists (select 1 from innovation i where i.title = v.title);