package pl.hubmalopolski.hub;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import java.sql.DriverManager;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MigrationV9Tests {
    @Test
    void upgradesLegacyRowsAndDefaultsNewIdeasToPending() throws Exception {
        try (var connection = DriverManager.getConnection("jdbc:h2:mem:migration-v9;MODE=PostgreSQL")) {
            try (var statement = connection.createStatement()) {
                statement.execute("create domain timestamptz as timestamp with time zone");
            }
            ScriptUtils.executeSqlScript(connection, new ClassPathResource("db/migration/V2__schema.sql"));
            try (var statement = connection.createStatement()) {
                statement.execute("create table resource (id bigint generated by default as identity primary key, kind varchar(50))");
                statement.execute("insert into innovation (title, status, region) values ('Test', 'nieznany', 'malopolska')");
                statement.execute("insert into idea (title, stage) values ('Stary', 'nieznany')");
                statement.execute("insert into resource (kind) values ('nieznany')");
            }

            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V9__accounts_catalog_and_matches.sql"));

            try (var statement = connection.createStatement()) {
                var innovation = statement.executeQuery("select status, region, created_at from innovation");
                innovation.next();
                assertEquals("ROZWOJ", innovation.getString("status"));
                assertEquals("MALOPOLSKA", innovation.getString("region"));
                assertEquals(true, innovation.getTimestamp("created_at") != null);

                var idea = statement.executeQuery("select stage, moderation_status from idea");
                idea.next();
                assertEquals("MYSL", idea.getString("stage"));
                assertEquals("APPROVED", idea.getString("moderation_status"));

                statement.execute("insert into idea (title, stage) values ('Nowy', 'MYSL')");
                var newIdea = statement.executeQuery("select moderation_status from idea where title = 'Nowy'");
                newIdea.next();
                assertEquals("PENDING", newIdea.getString(1));
            }
        }
    }
}
