package pl.hubmalopolski.hub;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import java.sql.DriverManager;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class MigrationV10V11Tests {
    @Test
    void keepsExistingKnowledgePublicAndStoresRepliesAndNotifications() throws Exception {
        try (var connection = DriverManager.getConnection("jdbc:h2:mem:migration-v10-v11;MODE=PostgreSQL")) {
            try (var statement = connection.createStatement()) {
                statement.execute("create domain timestamptz as timestamp with time zone");
            }
            ScriptUtils.executeSqlScript(connection, new ClassPathResource("db/migration/V2__schema.sql"));
            try (var statement = connection.createStatement()) {
                statement.execute("create table resource (id bigint generated by default as identity primary key, "
                        + "name varchar(255), url varchar(255), kind varchar(50))");
                statement.execute("insert into innovation (title, status) values ('Starsza innowacja', 'ROZWOJ')");
                statement.execute("insert into resource (name, url, kind) values "
                        + "('Poradnik', 'https://example.org', 'PUBLIKACJE')");
                statement.execute("insert into idea (title, stage) values ('Pomysł', 'MYSL')");
            }
            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V9__accounts_catalog_and_matches.sql"));
            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V10__knowledge_publication.sql"));
            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V11__idea_communication.sql"));

            try (var statement = connection.createStatement()) {
                var innovation = statement.executeQuery("select published from innovation");
                assertTrue(innovation.next());
                assertTrue(innovation.getBoolean(1));
                var resource = statement.executeQuery("select published from resource");
                assertTrue(resource.next());
                assertTrue(resource.getBoolean(1));

                statement.execute("insert into app_user (email, password_hash, display_name, role) "
                        + "values ('author@example.org', 'hash', 'Autor', 'MEMBER')");
                statement.execute("insert into app_user (email, password_hash, display_name, role) "
                        + "values ('staff@example.org', 'hash', 'Pracownik', 'STAFF')");
                statement.execute("insert into idea_reply (idea_id, author_user_id, body) "
                        + "values (1, 2, 'Odpowiedź')");
                statement.execute("insert into user_notification (recipient_user_id, idea_id, kind, title) "
                        + "values (1, 1, 'IDEA_REPLY', 'Nowa odpowiedź')");
                var replies = statement.executeQuery("select count(*) from idea_reply");
                replies.next();
                assertEquals(1, replies.getInt(1));
                var notifications = statement.executeQuery("select count(*) from user_notification");
                notifications.next();
                assertEquals(1, notifications.getInt(1));
            }
        }
    }
}
